<<<<<<< HEAD
# Generated by Django 4.2.7 on 2023-11-26 10:59

from django.db import migrations, models
=======
# Generated by Django 4.2.7 on 2023-11-30 16:39

from django.db import migrations, models
import django.db.models.deletion
>>>>>>> 3def1e2 (first commit)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Eid', models.IntegerField()),
                ('Ename', models.CharField(max_length=100)),
                ('job', models.CharField(max_length=100)),
                ('sal', models.IntegerField()),
=======
            name='Productdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('pid', models.IntegerField(primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.productdata')),
>>>>>>> 3def1e2 (first commit)
            ],
        ),
    ]
